/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.conexionsql;

/**
 *
 * @author david
 */
public class consulta_multi extends javax.swing.JFrame {
    PreparedStatement pst = null;
    ResultSet rst = null;
    Connection connDbc = null;
    conexionsql dbc = new conexionsql();
    /**
     * Creates new form consulta_multi
     */
    public consulta_multi() {
        initComponents();
        
    }

    private void fetchData(){
        connDbc = dbc.conectar();
        try{
            List<String> selectedColumns = new ArrayList<>();
            if (CheckBoxPorductorID.isSelected()) selectedColumns.add("productor.productorid");
            if (CheckBoxNombre.isSelected()) selectedColumns.add("productor.nombre");
            if (CheckBoxDireccion.isSelected()) selectedColumns.add("productor.dirección");
            if (CheckBoxTipoDeActividad.isSelected()) selectedColumns.add("productor.tipoactividad");
            if (CheckBoxFechaDeRegistro.isSelected()) selectedColumns.add("productor.fecharegistro");
            
            if (CheckBoxResiduoID.isSelected()) selectedColumns.add("residuo.residuoid");
            if (CheckBoxCodigoUnico.isSelected()) selectedColumns.add("residuo.codigounico");
            if (CheckBoxComposicionQuimica.isSelected()) selectedColumns.add("residuo.composicionquimica");
            if (CheckBoxCantidad.isSelected()) selectedColumns.add("residuo.cantidad");
            if (CheckBoxFechaDeGeneracion.isSelected()) selectedColumns.add("residuo.fechageneracion");
            
            if (selectedColumns.isEmpty()){
                JOptionPane.showMessageDialog(this, "Selecciona almenos una columna.");
                return;
            }
            
            String columns = String.join(", ", selectedColumns);
            String sqlSelectDataFromDatabase = "Select " + columns + " FROM productor INNER JOIN residuo ON productor.productorid = residuo.productorid;";
           
            System.out.println(sqlSelectDataFromDatabase);
            
            pst = connDbc.prepareStatement(sqlSelectDataFromDatabase);
            rst = pst.executeQuery();
            
            ResultSetMetaData metaData = rst.getMetaData();
            int columnCount = metaData.getColumnCount();
            
            DefaultTableModel model = new DefaultTableModel();
            for (int i = 1; i <= columnCount; i++){
                model.addColumn(metaData.getColumnName(i));
            }
            
            while(rst.next()){
                Object[] row = new Object[columnCount];
                for (int i=1; i<=columnCount; i++){
                    row[i-1] = rst.getObject(i);
                }
                model.addRow(row);
            }
            
            jTable1.setModel(model);
            
            rst.close();
            pst.close();
            connDbc.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        CheckBoxTipoDeActividad = new javax.swing.JCheckBox();
        CheckBoxFechaDeRegistro = new javax.swing.JCheckBox();
        CheckBoxCantidad = new javax.swing.JCheckBox();
        CheckBoxFechaDeGeneracion = new javax.swing.JCheckBox();
        CheckBoxNombre = new javax.swing.JCheckBox();
        CheckBoxDireccion = new javax.swing.JCheckBox();
        CheckBoxCodigoUnico = new javax.swing.JCheckBox();
        CheckBoxComposicionQuimica = new javax.swing.JCheckBox();
        CheckBoxResiduoID = new javax.swing.JCheckBox();
        CheckBoxPorductorID = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductoID", "ResiduoID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        CheckBoxTipoDeActividad.setText("Tipo de Actividad");

        CheckBoxFechaDeRegistro.setText("Fecha de Registro");

        CheckBoxCantidad.setText("Cantidad");

        CheckBoxFechaDeGeneracion.setText("Fecha de Generación");

        CheckBoxNombre.setText("Nombre ");
        CheckBoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxNombreActionPerformed(evt);
            }
        });

        CheckBoxDireccion.setText("Dirección");

        CheckBoxCodigoUnico.setText("Código Único");

        CheckBoxComposicionQuimica.setText("Composición Química");
        CheckBoxComposicionQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxComposicionQuimicaActionPerformed(evt);
            }
        });

        CheckBoxResiduoID.setText("ResiduoID");

        CheckBoxPorductorID.setText("ProductorID");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CheckBoxResiduoID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CheckBoxPorductorID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(CheckBoxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CheckBoxNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CheckBoxCodigoUnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CheckBoxComposicionQuimica, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                                .addGap(153, 153, 153))
                                            .addComponent(CheckBoxDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CheckBoxTipoDeActividad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckBoxFechaDeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckBoxFechaDeGeneracion)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(CheckBoxComposicionQuimica))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CheckBoxNombre)
                                    .addComponent(CheckBoxDireccion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBoxCodigoUnico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckBoxPorductorID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBoxResiduoID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckBoxCantidad)
                            .addComponent(CheckBoxTipoDeActividad)
                            .addComponent(CheckBoxFechaDeRegistro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxFechaDeGeneracion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MainView objinicio = new MainView();
        objinicio.setVisible(true);
        objinicio.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void CheckBoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fetchData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CheckBoxComposicionQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxComposicionQuimicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxComposicionQuimicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulta_multi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulta_multi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulta_multi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulta_multi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulta_multi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxCantidad;
    private javax.swing.JCheckBox CheckBoxCodigoUnico;
    private javax.swing.JCheckBox CheckBoxComposicionQuimica;
    private javax.swing.JCheckBox CheckBoxDireccion;
    private javax.swing.JCheckBox CheckBoxFechaDeGeneracion;
    private javax.swing.JCheckBox CheckBoxFechaDeRegistro;
    private javax.swing.JCheckBox CheckBoxNombre;
    private javax.swing.JCheckBox CheckBoxPorductorID;
    private javax.swing.JCheckBox CheckBoxResiduoID;
    private javax.swing.JCheckBox CheckBoxTipoDeActividad;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
