/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author david
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnagregar = new javax.swing.JButton();
        btnmostrartodo = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnConsultaAvanzada = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btnConsultaMultitabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnagregar.setText("Agregar Nuevo Registro");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnmostrartodo.setText("Mostrar Todos los Registros");
        btnmostrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrartodoActionPerformed(evt);
            }
        });

        btnmodificar.setText("Actualizar/Modificar Registro Existente");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnConsultaAvanzada.setText("Consulta Avanzada");
        btnConsultaAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaAvanzadaActionPerformed(evt);
            }
        });

        btnborrar.setText("Eliminar Registro Existente");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btnConsultaMultitabla.setText("Consulta Multitabla");
        btnConsultaMultitabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaMultitablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultaMultitabla)
                    .addComponent(btnConsultaAvanzada)
                    .addComponent(btnmodificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnagregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnmostrartodo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnborrar))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnagregar)
                .addGap(18, 18, 18)
                .addComponent(btnmostrartodo)
                .addGap(18, 18, 18)
                .addComponent(btnmodificar)
                .addGap(18, 18, 18)
                .addComponent(btnborrar)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaAvanzada)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaMultitabla)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        mostrar objmostrar = new mostrar();
        objmostrar.setVisible(true);
        objmostrar.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnConsultaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaAvanzadaActionPerformed
        consulta_avanzada objconsulta_avanzada = new consulta_avanzada();
        objconsulta_avanzada.setVisible(true);
        objconsulta_avanzada.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaAvanzadaActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        guardar objguardar = new guardar();
        objguardar.setVisible(true);
        objguardar.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnmostrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrartodoActionPerformed
        mostrar_todo objmostrar_todo = new mostrar_todo();
        objmostrar_todo.setVisible(true);
        objmostrar_todo.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnmostrartodoActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        Borrar objborrar = new Borrar();
        objborrar.setVisible(true);
        objborrar.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnConsultaMultitablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaMultitablaActionPerformed
        consulta_multi objmulti = new consulta_multi();
        objmulti.setVisible(true);
        objmulti.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaMultitablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaAvanzada;
    private javax.swing.JButton btnConsultaMultitabla;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnmostrartodo;
    // End of variables declaration//GEN-END:variables
}
